export function getRandomPastelColor(): string { // Generated by ChatGPT
  const hue = Math.floor(Math.random() * 360); // Random hue value between 0 and 359
  const saturation = Math.floor(Math.random() * 30) + 70; // Random saturation value between 70 and 100
  const lightness = Math.floor(Math.random() * 10) + 60; // Random lightness value between 60 and 70
  
  // Convert HSL values to RGB
  const hslToRgb = (h: number, s: number, l: number) => {
    const c = (1 - Math.abs(2 * l - 1)) * s;
    const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
    const m = l - c / 2;
    let r = 0, g = 0, b = 0;
    
    if (0 <= h && h < 60) {
      r = c; g = x; b = 0;
    } else if (60 <= h && h < 120) {
      r = x; g = c; b = 0;
    } else if (120 <= h && h < 180) {
      r = 0; g = c; b = x;
    } else if (180 <= h && h < 240) {
      r = 0; g = x; b = c;
    } else if (240 <= h && h < 300) {
      r = x; g = 0; b = c;
    } else if (300 <= h && h < 360) {
      r = c; g = 0; b = x;
    }
    
    const rgb = [(r + m) * 255, (g + m) * 255, (b + m) * 255];
    return rgb.map((value) => Math.round(value).toString(16).padStart(2, '0')).join('');
  };
  
  const hexColor = hslToRgb(hue, saturation / 100, lightness / 100);
  return `#${hexColor}`;
}